import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { db } from '@welcome-connect/firebase'
import { useEffect, useState } from 'react'
import { Users } from '@welcome-connect/firebase/@types/Users'

export default function Home() {
	const [data, setData] = useState<Users[] | null>(null)
	useEffect(() => {
		async function getData() {
			const data = await db.users.get()
			setData(data.docs.map(doc => doc.data()))
		}

		getData()
	}, [])
	console.log({ data })

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1>hello world</h1>
		</div>
	)
}
